version: '3'

services:
  app:
    build:
      context: .
      dockerfile: go/src/Dockerfile.local
    ports:
      - "3000:8080"
    volumes:
      - ./go/src/:/go/src
    tty: true

  db:
    image: postgres:15.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: det_voc
    ports:
      - "5432:5432"
