// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/jinzhu/gorm"
	"nothing-behind.com/sample_gin/packages/vocabulary/infra/postgres/repository"
	"nothing-behind.com/sample_gin/packages/vocabulary/usecase"
)

// Injectors from wire.go:

func InitVocabularyList(db *gorm.DB) usecase.ListVocabularies {
	vocabularyRepository := repository.NewVocabularyRepository(db)
	listVocabularies := usecase.NewListCategories(db, vocabularyRepository)
	return listVocabularies
}
