FROM golang:1.19-alpine

WORKDIR /go/src
COPY ./go/src .

RUN apk upgrade --update && apk --no-cache add git

RUN go get -u github.com/cosmtrek/air && go build -o /go/bin/air github.com/cosmtrek/air
RUN apk add --no-cache alpine-sdk build-base

CMD ["air", "-c", ".air.toml"]
